# ggc completion                                           -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_ggc_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"

  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_ggc_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'versions'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ggc_completions_filter "--help -h")" -- "$cur")
      ;;

    'publish'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ggc_completions_filter "--help -h")" -- "$cur")
      ;;

    'deploy'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ggc_completions_filter "--help -h")" -- "$cur")
      ;;

    'build'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ggc_completions_filter "--help -h")" -- "$cur")
      ;;

    'init'*)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ggc_completions_filter "--help -h javascript python ruby shell")" -- "$cur")
      ;;

    *)
      while read -r; do COMPREPLY+=("$REPLY"); done < <(compgen -W "$(_ggc_completions_filter "--help --version -h -v build deploy init publish versions")" -- "$cur")
      ;;

  esac
} &&
  complete -F _ggc_completions ggc

# ex: filetype=sh
